### ISSUE TITLE
I want to help me.

### ISSUE THREAD

**Issue by mosvict** [rioald/BaramangSwipe#1]
I made slide with baramangswipe.js.
And I added the buttons of prev and next.
When user click prev button, which function should i call?

for example, 
var obj = slider;
obj.previousElement();

It's not working. I want to help me.

**Comment by rioald** [comment]
hi, @gitshinesun .
thanks for posting to forgotten project :)

this swipe plugin was made by 7 years ago
nowadays good plugins were released.

- iSwiper
- OwlCarousel2

check above plugins.

or If you have to use it, check applied web page
http://m.sangsanguniv.com
http://m.sangsanguniv.com/res/js/baramangSwipeTemplate.js

and execute below code
`
BaramangSwipe.action.studentTalkSlider.nextElement();
`

you can see one of list are swipe to next

I hope the answer is not late.
thanks.
